apiVersion: v1
kind: Namespace
metadata:
  name: gitlab-ns

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab-deployment
  namespace: gitlab-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitlab
  template:
    metadata:
      labels:
        app: gitlab
    spec:

#for the time that you need deploy on k8s master node
#      tolerations:          
#        - key: "node-role.kubernetes.io/master"
#          operator: "Exists"
#          effect: "NoSchedule"

      containers:
        - name: web
          image: gitlab/gitlab-ce:latest
          ports:
            - containerPort: 443
              name: https
            - containerPort: 22
              name: ssh
          volumeMounts:
            - name: config-volume
              mountPath: /etc/gitlab
            - name: logs-volume
              mountPath: /var/log/gitlab
            - name: data-volume
              mountPath: /var/opt/gitlab
          env:
            - name: GITLAB_OMNIBUS_CONFIG
              value: |
                external_url 'http://88.218.17.100'             #this will display the url for you gitlab clonning
                gitlab_rails['gitlab_shell_ssh_port'] = 22
          resources:
            limits:
              memory: "6Gi"
            requests:
              memory: "1Gi"
      volumes:
        - name: config-volume
          persistentVolumeClaim:
            claimName: config-pvc
        - name: logs-volume
          persistentVolumeClaim:
            claimName: logs-pvc
        - name: data-volume
          persistentVolumeClaim:
            claimName: data-pvc
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: config-pv
  namespace: gitlab-ns
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /root/gitlab/config
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: logs-pv
  namespace: gitlab-ns
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /root/gitlab/logs
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-pv
  namespace: gitlab-ns
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /root/gitlab/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-pvc
  namespace: gitlab-ns
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-pvc
  namespace: gitlab-ns
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pvc
  namespace: gitlab-ns
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: gitlab-clusterip-svc
  namespace: gitlab-ns
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: gitlab
  type: ClusterIP
