apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gitlab-ui
  namespace: gitlab-ns
spec:
  defaultBackend:
    service:
      name: gitlab-clusterip-svc
      port:
        number: 443
  ingressClassName: nginx
  rules:
  - host: your-dns-fqdn-or-domain.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: gitlab-clusterip-svc
            port:
              number: 443
